### ISSUE TITLE
Just noticed it

### ISSUE THREAD

**Issue by andris9** [baudehlo/Boosto#1]
Pretty interesting, noticed this repo just now for the first time. I'm working on a similar project, [Wild Duck IMAP Server](https://github.com/wildduck-email/wildduck) that is a Node.js IMAP server using MongoDB as mail store. Wild Duck is already fully working, supports all the required IMAP RFCs and more but there's not plugin system yet even though I have thought about adding something.

**Comment by baudehlo** [comment]
Yeah I have basically abandoned this project because I really couldn't see
a use for a customizable IMAP server. That, and parsing IMAP commands in a
streaming manner looked a bit too hard.

Wild Duck looks like a good alternative.

**Comment by andris9** [comment]
Oh, yeah, I started also with a customizable IMAP server in mind (for example to show dynamic content as "emails in a mailbox") but quickly realized there's not much point in it, better to try to build an alternative for the existing filesystem based mail storage servers that are hard to scale or even back up.
